### ISSUE TITLE
Logging makes this library unusable on Google App Engine

### ISSUE THREAD

**Issue by andrewwatson** [kevinburke/rest#3]
Because the GAE runtime doesn't allow calls to syscall, the use of log15 for logging makes this library not compile.

**Comment by andrewwatson** [comment]
In my fork, i removed all the logging and it builds/runs fine.  I like to practice the idea that libraries shouldn't log anything and should only pass back results and errors.

**Comment by kevinburke** [comment]
cc @inconshreveable, thoughts? can we put the syscalls behind a `// +build appengine` flag maybe?

**Comment by kevinburke** [comment]
@andrewwatson - we got this resolved by updating the log15 dependency, right? should I close the ticket?
