### ISSUE TITLE
Consider supporting non-relative paths

### ISSUE THREAD

**Issue by kenkendk** [kevinburke/rest#8]
When using a pagination API or similar, the results often contain full urls.
Currently, this causes problems because the base url is always string concatenated with the input path.

This happens [in line 131](https://github.com/kevinburke/rest/blob/master/client.go#L131):
```
req, err := http.NewRequest(method, c.Base+path, body)
```

A fix would be to perform proper concatenation, but I am not sure if you want to force the library to always use the base path.

Suggested fix:
```
base, err := url.Parse(c.Base)
if err != nil {
	return nil, err
}
fragment, err := url.Parse(path)
if err != nil {
	return nil, err
}
fullpath := base.ResolveReference(fragment)
req, err := http.NewRequest(method, fullpath.String(), body)
```

**Comment by kevinburke** [comment]
Thanks, I'll try to take a look at this this weekend... FYI I have to do something similar in the twilio-go library I maintain so I'll see what I can do.

Kevin

**Comment by kevinburke** [comment]
Fixed... I just set NewRequest to strip the beginning of path if it's an exact match of the `client.Base` value. If you update to 2.2, it should fix the issue!

**Comment by kenkendk** [comment]
It fixes the issue that I found, but there are many subtle pitfalls with this approach. The hostname could be different, port number could be included, and others things.

**Comment by kevinburke** [comment]
Sure, but other approaches also have downsides (bigger API, more invasive behavior). If we run into other problems we can fix them as they arise.
